### ISSUE TITLE
Ratelimit

### ISSUE THREAD

**Issue by zerebos** [dylan-dang/BetterDiscordPlugins#1]
Please ratelimit your fetches or else this will cause spam to Discord https://github.com/dylan-dang/BetterDiscordPlugins/blob/2541fc2452e4553e2a764ec4295e22d6f2405948/PreviewMessageLinks.plugin.js#L99

**Comment by emmajay1204** [comment]
I’d like to work with you! You seem at face value a decent human being that could help me with my cause & projects
