### ISSUE TITLE
[BUG] Highlighted Text Deselected

### ISSUE THREAD

**Issue by zluckytraveler** [dylan-dang/BetterDiscordPlugins#13]
When highlighting text and the cursor is moved outside of the text box the highlighted text will be removed.

https://user-images.githubusercontent.com/97180817/185640396-a0395210-a4f0-4808-8c20-9585c581b864.mov

https://user-images.githubusercontent.com/97180817/185640404-8f4052e1-1627-4960-90b5-edaf3055fb44.mov

**Comment by furuochen-dev** [comment]
This is not fixed at all, is this intended?

**Comment by furuochen-dev** [comment]
(also Spoilers got unspoiled)

**Comment by furuochen-dev** [comment]
wait sorry it's fixed in the newest version, but why isn't it on BetterDiscord Plugin List though

**Comment by dylan-dang** [comment]
Yeah, sorry about that. Plugin review and approval takes a while. So plugin updates won't be reflected on the BetterDiscord plugin list for a while, a few months more than likely. I recently changed the plugin directory to a dist folder for better organization, which required taking my old listing down and resubmitting as a new one, so until then the only way to download this plugin is through here.
