### ISSUE TITLE
[PreviewMessageLinks] Selection resets when hovered outside of message

### ISSUE THREAD

**Issue by maenDisease** [dylan-dang/BetterDiscordPlugins#3]
Text selections and emote popouts reset hovering outside of the message container.

![gif2](https://user-images.githubusercontent.com/90428263/163725613-fa6b1ee2-013c-42c7-a9f4-1a84d553cc56.gif)

**Comment by FiraliaDev** [comment]
Having this problem as well with text selection, @ mention popouts, and emote popouts. Sticker popouts seem to be the only thing not affected. Fix this please 🙏

**Comment by KaKi87** [comment]
I'm experiencing the same issue and found this plugin to be responsible by elimination process.
