### ISSUE TITLE
Plugin could not be constructed

### ISSUE THREAD

**Issue by Katzenwerfer** [dylan-dang/BetterDiscordPlugins#9]
Hi, I am currently getting this error whenever BD tries to load the plugin.

![image](https://user-images.githubusercontent.com/53267697/182301209-72f72a8e-2353-46c0-9fb0-7e76e13f7ada.png)

If any extra info, like logs and such, could be useful I am happy to provide it.

**Comment by Apraxed** [comment]
> Its known. Discord broke many Plugins with the last update

_Originally posted by @HypedDomi in https://github.com/Strencher/BetterDiscordStuff/issues/225#issuecomment-1201825082_
